collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

url: https://dawson-robotics.github.io
baseurl: /Website-3.0

languages: ["en", "fr"]
exclude_from_localization: ["assets"]
defaultLang: en
languageNames:
  en: English
  fr: Français
  
repository: Dawson-Robotics/Website-3.0

sass:
  style: compact # possible values: nested expanded compact compressed