collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "Website-3.0/authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "Website-3.0/posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
